### ISSUE TITLE
 (Feature) Manage created crowdsale contracts

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/ico-wizard#323]
**Rationale**
Users create multiple contracts using the wizard, usually for testing purposes. They need:
- to return back to their contracts without bookmarking them
- have the ability to modify updatable tiers
- have the ability to finalized contracts

**Implementation** 
On creating the crowdsale page there is a new button "Choose contract". It appears only if there is a crowdsale contract created by the active and unlocked wallet. The page will poll user's wallet for previously created contracts by the wizard.
 
![image](https://user-images.githubusercontent.com/424628/32289722-c0ea47b6-bef4-11e7-837c-bde333327e59.png)

If the button is active a list of crowdsales appears. Crowdsale name should be replaced to contract address, the name of a token, ticker, and date of creation. 
![image](https://user-images.githubusercontent.com/424628/32299373-a6cd814a-bf12-11e7-9d05-97320af883e3.png)

Updates of tier:

All tiers of the crowdsale are displayed. If tier itself or fields of a tier are not updatable then values are read-only.

Finalize button:

There is a finalize button to finalize the crowdsale. Should show a popup with yes/no and warning after pressing it. 
Text:
"Are you sure to finalize the crowdsale? After finalization, it's not possible to buy tokens, all tokens will be movable, reserved tokens will be issued. Press Yes to finalize, and NO to close this dialog."

Whitelists:

List of current whitelisted addresses is shown. It's possible to add an address to whitelist. 
If whitelisted address added in the state  

![image](https://user-images.githubusercontent.com/424628/32299395-b206c0da-bf12-11e7-9c06-12682c78ebab.png)

**Comment by igorbarinov** [comment]
open questions
- [ ] how to get ABI for the contract. should we ask for it before opening configuration page?

**Comment by vbaranov** [comment]
ABI is static. But if we assume, that the interface of the crowdsale contract can be changed in the future releases, yes, we need to ask ABI before opening configuration page.

**Comment by xirkle** [comment]
Do I need to create multiple smart contracts in order to see the "choose contract" button? How do I modify one existing smart contract before or after the start date? Thanks!

**Comment by igorbarinov** [comment]
@xirkle this PR is only for future. At the moment, you have to call function directly
e.g. to change max cap please refer to this wiki page https://github.com/oraclesorg/ico-wizard/wiki/Change-max-cap-for-tier

**Comment by fvictorio** [comment]
Some thoughts on this:

- Since this feature is pretty big, I propose splitting it in multiple PRs. We can hide the button until all the functionality is there or, if you don't want to merge anything into master until everything is done, we can use a feature branch.

- Regardless of what we choose, @fernandomg is going to start working on the frontend with some mocked data. He will make a PR with the "Choose contract" button and a mocked list of contracts. Meanwhile, I'll start working on the smart contracts side of the feature.

- I think having a registry of deployed contracts, mapping addresses to contracts, may be the best option. This would mean an extra step in the deployment, but it's probably worth it. I am going to make another comment later with a detailed design of the registry, so that you can give me some feedback, but my initial idea is to map each address to a list of structs. Each struct would have something like `(contractId, contractAddress, extraData)`. The extra data can be a serialized JSON; that way we can be flexible about what we put there (for example, the version of the contract, when it was deployed, or whatever we want).

**Comment by fvictorio** [comment]
I've been working on the registry (see oraclesorg/ico#7 for the contract) but there is something that I'm not sure how to handle.

Since the registry will be the same for each user, it will need to be deployed in each network, and the dapp will need to know the address of the registry (the ABI can be fetched like we do with the other contracts). We have some options here:

1. Hardcode the address of the Registry for each network. This would mean having a map from networkId to the address of the registry. The problem here is that `ganache-cli` creates a different network id each time you run it, but we could agree to use always the same one. Besides that, if we use the deterministic mode (`-d` flag), and the first thing we do is to deploy the registry, then the address will always be the same.
2. Same as 1, but have the map from network to contract address as a stringified JSON in an environment variable. This is more flexible, although a llittle more involved. It would also mean that the deploy configuration needs to be modified to add that environment variable, but that should be easy.
3. Use [ENS](https://ens.domains/). I guess the service exists in the testnets (not sure though), but I don't know how would we do in dev mode. Maybe we could have an optional environment variable and, if the name is not found in ENS, the environment variable would be used.

Thoughts on this?

I've already made some work that is close to option 2, I will make a PR as soon as I have something that can be deployed.

**Comment by fernandomg** [comment]
I was checking how to retrieve data from the crowdsale address only, and found a couple of issues.

1.- I'm not finding a way to retrieve the tier's name (seems like it's not even stored)
2.- As earlyParticipantWhitelist is a mapping I can't retrieve the whitelisted addresses and its min/max cap. Or the idea is to allow to add addresses to the whitelist but not list them?

**Comment by vbaranov** [comment]
Good questions! Let's extend CrowdsaleExt contract.

>1.- I'm not finding a way to retrieve the tier's name (seems like it's not even stored)

https://github.com/oraclesorg/ico/issues/8

>2.- As earlyParticipantWhitelist is a mapping I can't retrieve the whitelisted addresses and their min/max cap. Or the idea is to allow to add addresses to the whitelist but not list them?

https://github.com/oraclesorg/ico/issues/9
