### ISSUE TITLE
Can not complete Invest test "Transaction failed try again"

### ISSUE THREAD

**Issue by jlitz** [poanetwork/ico-wizard#455]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*     https://sokol.poa.network  

### If you were able to create it, what is the URL of your crowdsale?

*Your answer*https://wizard.oracles.org/crowdsale?addr=0xec57b9ea10fda1d7F7Bc4F26BcCd8Bc641686687&networkID=77

### Do you have screenshots showing the problem?

*Your answer*
![metamaskerror](https://user-images.githubusercontent.com/29810797/34656982-8a26ea7e-f3ef-11e7-9c41-fda80ec770bf.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

*Your answer*

---
![screenshot_1](https://user-images.githubusercontent.com/29810797/34657007-c15e031a-f3ef-11e7-830c-33bbff0493ea.png)
![screenshot_2](https://user-images.githubusercontent.com/29810797/34657019-cd80f6e8-f3ef-11e7-88c4-cbb62278c39e.png)

**Comment by jlitz** [comment]
Invest page url    https://wizard.oracles.org/invest?addr=0xec57b9ea10fda1d7F7Bc4F26BcCd8Bc641686687&networkID=77

**Comment by igorbarinov** [comment]
Did you check wiki article about possible transactions failures ?
https://github.com/poanetwork/ico-wizard/wiki/ICO-Wizard-Possible-Tx-Failures

**Comment by vbaranov** [comment]
@jlitz Your crowdsale is extremely short:

starts at: Sunday, 7 January 2018 г., 15:02:00
ends at: Sunday, 7 January 2018 г., 15:05:00

I don't see, the time of your investing try, but the time of log file creation is Sunday, 7 January 2018 г., 16:42:40.874.

So, I believe the issue is that you tried to buy after the end of crowdsale. If you can repeat the issue within the valid time interval, please, let us know and reopen the issue.
